title: Aloysius Lim | Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://Aloylim.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aloysius Lim # add your name
author-img:  Homepage Image.jpg # add your photo
about-author: I strive to turn Data into Insights, and Insights into Change. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Aloylim # add your Github handle
social-linkedin: aloysius-lim-509429122 # add your Linkedin handle
social-email: aloylim98@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
